# ClientsmanagerAPI CI Pipeline: 
# Configures CI Pipeline.
# Configures Restore, Build, Test and Publish tasks.
# Publishes build artifact to Azure Pipelines


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
  displayName: 'ClientsManager API Restore'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'ClientsManager API Build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'
    arguments: '--configuration $(buildConfiguration)'
    testRunTitle: 'ClientsManagerAPI_Tests_Run'
  displayName: 'ClientsManager API Test'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration)  --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
  displayName: 'ClientsManager API Publish'

#take all the files in $(Build.ArtifactStagingDirectory) and upload them as an artifact of your build
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
