// <auto-generated />
using System;
using ClientsManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClientsManager.Data.Migrations
{
    [DbContext(typeof(ClientsManagerDbContext))]
    [Migration("20200716034715_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ClientsManager.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeType_Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeType_Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeType_Id = 1,
                            Name = "John Smith",
                            Position = "Junior Lawyer"
                        },
                        new
                        {
                            Id = 2,
                            EmployeeType_Id = 1,
                            Name = "Jane Doe",
                            Position = "Junior Lawyer"
                        },
                        new
                        {
                            Id = 3,
                            EmployeeType_Id = 1,
                            Name = "Michael Jones",
                            Position = "Junior Lawyer"
                        },
                        new
                        {
                            Id = 4,
                            EmployeeType_Id = 1,
                            Name = "Eliza Deer",
                            Position = "Junior Lawyer"
                        },
                        new
                        {
                            Id = 5,
                            EmployeeType_Id = 2,
                            Name = "Peter Granger",
                            Position = "Partner"
                        },
                        new
                        {
                            Id = 6,
                            EmployeeType_Id = 2,
                            Name = "Mary Osterfitz",
                            Position = "Partner"
                        });
                });

            modelBuilder.Entity("ClientsManager.Models.EmployeeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Worker"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Manager"
                        });
                });

            modelBuilder.Entity("ClientsManager.Models.TimeFrame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Finish_DateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Start_DateTime")
                        .HasColumnType("DATETIME2 (7)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id");

                    b.ToTable("TimeFrames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "this is the timeframe 1",
                            Employee_Id = 1,
                            Finish_DateTime = new DateTime(2020, 6, 20, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 120.50m,
                            Start_DateTime = new DateTime(2020, 6, 20, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "timeframe 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "this is the timeframe 2",
                            Employee_Id = 1,
                            Finish_DateTime = new DateTime(2020, 6, 21, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            Price = 400m,
                            Start_DateTime = new DateTime(2020, 6, 21, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "timeframe 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "this is the timeframe 3",
                            Employee_Id = 2,
                            Finish_DateTime = new DateTime(2020, 6, 23, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Price = 300.50m,
                            Start_DateTime = new DateTime(2020, 6, 23, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            Title = "timeframe 3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "this is the timeframe 4",
                            Employee_Id = 3,
                            Finish_DateTime = new DateTime(2020, 6, 20, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 120.50m,
                            Start_DateTime = new DateTime(2020, 6, 20, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "timeframe 4"
                        },
                        new
                        {
                            Id = 5,
                            Description = "this is the timeframe 5",
                            Employee_Id = 3,
                            Finish_DateTime = new DateTime(2020, 6, 21, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            Price = 400m,
                            Start_DateTime = new DateTime(2020, 6, 21, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "timeframe 5"
                        },
                        new
                        {
                            Id = 6,
                            Description = "this is the timeframe 6",
                            Employee_Id = 4,
                            Finish_DateTime = new DateTime(2020, 6, 23, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Price = 300.50m,
                            Start_DateTime = new DateTime(2020, 6, 23, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            Title = "timeframe 6"
                        },
                        new
                        {
                            Id = 7,
                            Description = "this is the timeframe 7",
                            Employee_Id = 5,
                            Finish_DateTime = new DateTime(2020, 6, 23, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Price = 300.50m,
                            Start_DateTime = new DateTime(2020, 6, 23, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            Title = "timeframe 7"
                        },
                        new
                        {
                            Id = 8,
                            Description = "this is the timeframe 8",
                            Employee_Id = 5,
                            Finish_DateTime = new DateTime(2020, 6, 23, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Price = 300.50m,
                            Start_DateTime = new DateTime(2020, 6, 23, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            Title = "timeframe 8"
                        },
                        new
                        {
                            Id = 9,
                            Description = "this is the timeframe 9",
                            Employee_Id = 6,
                            Finish_DateTime = new DateTime(2020, 6, 23, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Price = 300.50m,
                            Start_DateTime = new DateTime(2020, 6, 23, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            Title = "timeframe 9"
                        });
                });

            modelBuilder.Entity("ClientsManager.Models.Employee", b =>
                {
                    b.HasOne("ClientsManager.Models.EmployeeType", "EmployeeType")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeType_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClientsManager.Models.TimeFrame", b =>
                {
                    b.HasOne("ClientsManager.Models.Employee", "Employee")
                        .WithMany("TimeFrames")
                        .HasForeignKey("Employee_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
