// <auto-generated />
using System;
using ClientsManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClientsManager.Data.Migrations
{
    [DbContext(typeof(ClientsManagerDBContext))]
    [Migration("20200628000746_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ClientsManager.Models.TimeFrame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Finish_DateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Start_DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TimeFrames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "this is the timeframe 1",
                            Employee_Id = 1,
                            Finish_DateTime = new DateTime(2020, 6, 20, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 120.50m,
                            Start_DateTime = new DateTime(2020, 6, 20, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "timeframe 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "this is the timeframe 2",
                            Employee_Id = 1,
                            Finish_DateTime = new DateTime(2020, 6, 21, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            Price = 400m,
                            Start_DateTime = new DateTime(2020, 6, 21, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "timeframe 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "this is the timeframe 3",
                            Employee_Id = 2,
                            Finish_DateTime = new DateTime(2020, 6, 23, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Price = 300.50m,
                            Start_DateTime = new DateTime(2020, 6, 23, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            Title = "timeframe 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
